### ISSUE TITLE
PHP warnings on vagrant up / vagrant provision with WPSeed

### ISSUE THREAD

**Issue by akolinski** [flurinduerst/WPDistillery#101]
I have created a new instance of WPDistillery. I have followed steps 1 to 4 here https://github.com/flurinduerst/WPDistillery#setup. At step 4 running `vagrant up` the provisioning of the box is halted. I had to run `vagrant plugin install vagrant-vbguest` and then `vagrant vbguest`. Then I ran `vagrant reload` and then `vagrant provision`. Whilst the box was trying to provision again a bunch of errors popped up. I have attached the log which outlines functions and line numbers of the errors.

```
default: [=== CONFIGURE THEME ===]
    default: »»» downloading WPSeed...
    default: Downloading installation package from https://github.com/flurinduerst/WPSeed/archive/master.zip...
    default: Unpacking the package...
    default: Installing the theme...
    default: Renamed Github-based project from 'WPSeed-master' to 'WPSeed'.
    default: PHP Warning:  fopen(/var/www/public/wp-content/upgrade/master-tSIPFU/WPSeed/style.css): failed to open stream: No such file or directory in /var/www/public/wp-includes/functions.php on line 5782
    default: Warning: fopen(/var/www/public/wp-content/upgrade/master-tSIPFU/WPSeed/style.css): failed to open stream: No such file or directory in /var/www/public/wp-includes/functions.php on line 5782
    default: PHP Warning:  fread() expects parameter 1 to be resource, boolean given in /var/www/public/wp-includes/functions.php on line 5785
    default: Warning: fread() expects parameter 1 to be resource, boolean given in /var/www/public/wp-includes/functions.php on line 5785
    default: PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/public/wp-includes/functions.php on line 5788
    default: Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/public/wp-includes/functions.php on line 5788
    default: Warning: The package could not be installed. "The <code>style.css</code> stylesheet doesn&#8217;t contain a valid theme header."
    default: Theme update failed.
    default: Warning: The 'https://github.com/flurinduerst/WPSeed/archive/master.zip' theme could not be found.
    default: Error: No themes installed.
    default:
    default: »»» aborting WPDistillery setup!
    default: bash: line 5: xit: command not found

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
