### ISSUE TITLE
Error on vagrant up with WPSeed

### ISSUE THREAD

**Issue by HarunKilic** [flurinduerst/WPDistillery#102]
When i try to vagrant up with default config, i get the following error: 

```    default: Success: Switched to 'WPSeed' theme.
    default: »»» removing default themes...
    default: » removing twentyfifteen...
    default: PHP Parse error:  syntax error, unexpected end of file in /var/www/public/wp-content/themes/WPSeed/functions/functions-dev.php on line 236
    default: Parse error: syntax error, unexpected end of file in /var/www/public/wp-content/themes/WPSeed/functions/functions-dev.php on line 236
    default: Error: There has been a critical error on your website.Learn more about debugging in WordPress. There has been a critical error on your website.
    default:
    default: »»» aborting WPDistillery setup!```

**Comment by Stewie4848** [comment]
I worked around this error by editing the config.yml and setting a default wordpress theme:
```
theme:
  name: twentyfifteen
  url: "https://downloads.wordpress.org/theme/twentyfifteen.2.9.zip"
  rename: ""
  remove: ""
```
