### ISSUE TITLE
Cannot connect after setting up with default configuration

### ISSUE THREAD

**Issue by johnpitchko** [flurinduerst/WPDistillery#30]
Installed WPDistillery in a fresh directory following all instructions posted. Observed a few issues during set up:
1. Connection refused when installing wordpress

```
»»» installing wordpress...
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 1025 (Errno::ECONNREFUSED)
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `open'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `tcp_socket'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:551:in `block in do_start'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `call'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:550:in `do_start'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:238:in `deliver'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/bin/catchmail:71:in `<top (required)>'
    from /home/vagrant/.rbenv/versions/2.2.2/bin/catchmail:23:in `load'
    from /home/vagrant/.rbenv/versions/2.2.2/bin/catchmail:23:in `<main>'
Success: WordPress installed successfully.
Success: Updated user 1.
```
1. Error during theme installation

```
»»» installing/activating WPSeed...
mv: cannot stat ‘wp-content/themes/WPSeed-master’: No such file or directory
Do you want to continue anyway? (y/n) y
»»» continuing WPDistillery setup...
```

No other error messages detected.

When attempting to load wpdistillery.dev, received the following Google error: `ERR_CONNECTION_TIMED_OUT`

**Comment by ShaneShipston** [comment]
In regards to the first error you received it is trying to send out the welcome email for the admin account that was created. You can either add `--skip-email` to the end of line 79 in the setup.sh or activate mail catcher before installation. You can refer to https://box.scotch.io/ for running mail catcher.

**Comment by realnerdo** [comment]
Hi, I love this project it's very cool.

I also get this error:

```
»»» installing/activating WPSeed...
»»» renaming WPSeed to CustomName...
mv: cannot stat 'wp-content/themes/WPSeed-master': No such file or directory
Do you want to continue anyway? (y/n) y
»»» continuing WPDistillery setup...
Error: The 'CustomName' theme could not be found.
Do you want to continue anyway? (y/n) y
»»» continuing WPDistillery setup...
```

I have the default config, only added a rename name:

```
# THEME
#################################################################

# theme to install, choose new name in 'rename' or leave empty
theme:
  name: WPSeed
  rename: "CustomName"
  url: "https://github.com/flurinduerst/WPSeed/archive/master.zip"
  # add branch (e.g. master) or leave empty ("") if theme is not downloaded from a git repository
  source_branch: master
```

@ShaneShipston Is there anything I can do?
@johnpitchko Did you find a solution?

Thank you for your help!
Cheers.
Asael.

**Comment by Matt-Owens** [comment]
I'm facing the same problem @johnpitchko Let us know if you found a solution.

**Comment by flurinduerst** [comment]
EDIT: Fixed, see my comment below

Hi @johnpitchko, @realnerdo, @Matt-Owens thanks for submitting this issue. It looks like there's a bug in the setup when installing the theme (with or without renaming it, as it looks like).

For now, you can run the setup without cleaning-up (deleting) the default themes, and without installing the "new" theme using the following configuration at `# WPDISTILLERY SETUP` at the bottom of `config.yml` starting at line 100 (changed `theme` and `cleanup_themes` to `false` to bypass the bug):

```
setup:
  wp: true
  settings: true
  theme: false
  plugins: true
  cleanup: true
    comment: true
    posts: true
    files: true
    themes: false
```

Let me know if this temporary workaround works for you, **I will fix this asap**.
