### ISSUE TITLE
Install fails at theme

### ISSUE THREAD

**Issue by codeclinic** [flurinduerst/WPDistillery#85]
If I try running this (on Win 10) the install / vagrant up fails with the following notice:

```
    default: [=== CONFIGURE THEME ===]
    default: »»» downloading WPSeed...
    default: Downloading installation package from https://github.com/flurinduerst/WPSeed/archive/master.zip...
    default: Unpacking the package...
    default: Installing the theme...
    default: Renamed Github-based project from 'WPSeed-master' to 'WPSeed'.
    default: Removing the old version of the theme...
    default: Theme updated successfully.
    default: Success: Installed 1 of 1 themes.
    default: »»» installing/activating WPSeed...
    default: Error: The 'WPSeed' theme could not be found.
    default:
    default: »»» aborting WPDistillery setup!
    default: bash: line 5: xit: command not found

```

I also see a lot of:
`default: Warning: Failed to create directory '/root/.wp-cli/cache/': mkdir(): Permission denied.`

If I disable themes in the config file the install works, but I still get lots of the cache warnings.
