### ISSUE TITLE
Unable to Install on ScotchBox Pro

### ISSUE THREAD

**Issue by jljr222** [flurinduerst/WPDistillery#86]
```
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'scotch/box-pro' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: password
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit nfs mounting file.
[NFS] Status: running
==> default: Mounting NFS shared folders...
==> default: Running provisioner: shell...
    default: Running: inline script
    default: Converting Files for Windows
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: dos2unix is already the newest version (7.3.4-3).
    default: 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
    default: dos2unix:
    default: converting file wpdistillery/config.yml to Unix format...
    default: dos2unix:
    default: converting file wpdistillery/provision.sh to Unix format...
    default: dos2unix:
    default: converting file wpdistillery/wpdistillery.sh to Unix format...
==> default: Running provisioner: shell...
    default: Running: ***/vagrant-shell20181007-2412-19tqkhw.sh
    default: == Update WP CLI (re-install) ==
    default: WP-CLI Update done
    default: == Run WPDistillery ==
    default: ========== WPDISTILLERY START ==========
    default: »»» creating root dir "public"...
    default: [=== INSTALL WORDPRESS ===]
    default: »»» downloading WordPress...
    default: Downloading WordPress 4.9.8 (en_US)...
    default: Warning: Failed to create directory '/root/.wp-cli/cache/': mkdir(): Permission denied.
    default: md5 hash verified: c4e7d68b5c382fbbaf547f2b2d42c198
    default: Success: WordPress downloaded.
    default: »»» creating wp-config...
    default: Success: Generated 'wp-config.php' file.
    default: »»» installing WordPress...
    default: PHP Fatal error:  Uncaught Error: Class 'WP_Hook' not found in /var/www/public/wp-includes/plugin.php:31
    default: Stack trace:
    default: #0 /var/www/public/wp-settings.php(21): require_once()
    default: #1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1188): require('/var/www/public...')
    default: #2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1111): WP_CLI\Runner->load_wordpress()
    default: #3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    default: #4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    default: #5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(23): WP_CLI\bootstrap()
    default: #6 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
    default: #7 /usr/local/bin/wp(4): include('phar:///usr/loc...')
    default: #8 {main}
    default:   thrown in /var/www/public/wp-includes/plugin.php on line 31
    default:
    default: »»» aborting WPDistillery setup!
    default: bash: line 5: xit: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I am using the latest version of ScotchBox Pro which has the most updated WP_CLI. I am not sure what I am doing wrong with my installation. I had no problems installing WordPress manually on ScotchBox Pro, but thought using WPDistillery would make this much easier for me.

I'm on Windows 10 if my OS helps at all. Let me know if you need any additional information.

Here is my vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# WPDistillery Vagrantfile using Scotch Box
# Check out https://box.scotch.io to learn more about Scotch Box
#
# File Version: 1.2.1

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box-pro"
    config.vm.hostname = "scotchbox"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "private_network", ip: "192.168.33.10"

    # Use vagrant-winnfsd if available https://github.com/flurinduerst/WPDistillery/issues/78
    if Vagrant.has_plugin? 'vagrant-winnfsd'
      config.vm.synced_folder ".", "/var/www",
        nfs: true,
        mount_options: [
        'nfsvers=3',
        'vers=3',
        'actimeo=1',
        'rsize=8192',
        'wsize=8192',
        'timeo=14'
        ]
    else
      config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    end

    # WPDistillery Windows Support
    if Vagrant::Util::Platform.windows?
      config.vm.provision "shell",
      inline: "echo \"Converting Files for Windows\" && sudo apt-get install -y dos2unix && cd /var/www/ && dos2unix wpdistillery/config.yml && dos2unix wpdistillery/provision.sh && dos2unix wpdistillery/wpdistillery.sh",
      run: "always", privileged: false
    end

    # Run Provisioning – executed within the first `vagrant up` and every `vagrant provision`
    config.vm.provision "shell", path: "wpdistillery/provision.sh"

    # OPTIONAL - Update WordPress and all Plugins on vagrant up – executed within every `vagrant up`
    config.vm.provision "shell", inline: "echo \"== Update WordPress & Plugins ==\" && cd /var/www/public && wp core update && wp plugin update --all", run: "always", privileged: false

    # OPTIONAL - Enable NFS. Make sure to remove line 13 (See https://stefanwrobel.com/how-to-make-vagrant-performance-not-suck)
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

end
```

Also here is my config.yml file:
```
# Configuration for WPDistillery executed by setup.sh
#
# Author: Flurin Dürst
# URL: https://wpdistillery.org
#
# For detailed instructions on this file read the config.yml-documentation at
# https://wpdistillery.org/documentation/config-yml-documentation/
#
# File Version: 1.8.3


# INSTALLATION
#################################################################

# WordPress version
wpversion: latest

# language/timezone
wplocale: en_US
timezone: "America/New_York"

# admin user settings
admin:
  user: -- snipped --
  password: -- snipped --
  email: -- snipped --
  first_name: -- snipped --
  last_name: -- snipped --

# scotch box db access
db:
  name: scotchbox
  user: root
  pass: root
  prefix: wp_

# SETTINGS
#################################################################

wpsettings:
  url: -- snipped --
  title: -- snipped --
  description: -- snipped --
  permalink_structure: "/%postname%/"
  thumbnail_width: 150
  thumbnail_height: 150
  medium_width: 300
  medium_height: 300
  large_width: 1024
  large_height: 1024
  # use page as frontpage
  page_on_front: true
  # define frontpage name (requires `page_on_front: true`)
  frontpage_name: Homepage
  # automatic conversion of smilies
  convert_smilies: false

# THEMES
#################################################################

# install a custom theme via url, rename it and remove the default themes
theme:
  name: WPSeed
  url: "https://github.com/flurinduerst/WPSeed/archive/master.zip"
  rename: ""
  remove:
    - twentyfifteen
    - twentysixteen
    - twentyseventeen


# PLUGINS
#################################################################

# plugins to install & activate
plugins_active:
  - disable-comments
  - disable-emojis
  - favicon-by-realfavicongenerator
  - regenerate-thumbnails
  - simple-page-ordering
  - advanced-custom-fields
  - autodescription
  - dont-muck-my-markup
  - gdpr-framework
  - redirection
  - cookie-law-info
  - relevanssi

# plugins to install
plugins_inactive:
  #migration
  - all-in-one-wp-migration
  #development
  - search-and-replace
  #security/backup
  - two-factor
  - backwpup
  - really-simple-ssl
  # gdpr
  - gdpr-for-gravity-forms

# WPDISTILLERY SETUP
####################################################################
# if you don't want the setup to run all tasks, set them to false

setup:
  wp: true
  settings: true
  theme: false
  plugins: true
  cleanup: true
  # adjust what data you want to be deleted within the cleanup (requires `cleanup: true`)
  comment: true
  posts: true
  files: true
```

Note, I set the "theme" setup config to false because of the issue reported at #85
