### ISSUE TITLE
Install script crashes using default options

### ISSUE THREAD

**Issue by johnpitchko** [flurinduerst/WPDistillery#94]
Tried installing wpdistillery with default options. Have not made any modifications to Vagrantfile or config.yml; only using defaults included in repo. Encountering the following error during provisioning:

```
    default: [=== CONFIGURE THEME ===]
    default: »»» downloading WPSeed...
    default: Downloading installation package from https://github.com/flurinduerst/WPSeed/archive/master.zip...
    default: Unpacking the package...
    default: Installing the theme...
    default: Renamed Github-based project from 'WPSeed-master' to 'WPSeed'.
    default: Removing the old version of the theme...
    default: Theme updated successfully.
    default: Success: Installed 1 of 1 themes.
    default: »»» installing/activating WPSeed...
    default: PHP Parse error:  syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) in /var/www/public/wp-content/themes/WPSeed/functions/functions-dev.php on line 195
    default: Parse error: syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) in /var/www/public/wp-content/themes/WPSeed/functions/functions-dev.php on line 195
    default:
    default: »»» aborting WPDistillery setup!
    default: bash: line 5: xit: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
